### ISSUE TITLE
报错Return value of TypechoPlugin\Notice\libs\Version::getNewReleaseFromGithub() must be of the type string, null returned，无法进入设置页面

### ISSUE THREAD

**Issue by yburger** [RainshawGao/Typecho-Plugin-Notice#11]
Return value of TypechoPlugin\Notice\libs\Version::getNewReleaseFromGithub() must be of the type string, null returned
启用时和后面进入设置页面时，报这个错误

**Comment by yburger** [comment]
好像是Version.php文件里github地址过时了，手动更改后正常了

**Comment by Rainshaw** [comment]
升级到最新版1.0.6即可
