### ISSUE TITLE
qmsg推送失败，提示数组错误

### ISSUE THREAD

**Issue by OuOumm** [RainshawGao/Typecho-Plugin-Notice#2]
直接提示了array啥的。

**Comment by Rainshaw** [comment]
哪个功能？评论是异步接口应该不会报错的。

**Comment by OuOumm** [comment]
qmsg酱= =我用的是最新开发板，直接提示array了。发送失败：array

**Comment by OuOumm** [comment]
> 哪个功能？评论是异步接口应该不会报错的。

而且下载的版本是0.7.0，但是安装之后提示的还是0.6.0。。。。qmsg酱测试推送的时候直接报错  爆了一个array错误，发送失败：array，这样子的。

**Comment by OuOumm** [comment]
> 哪个功能？评论是异步接口应该不会报错的。

而且下载的版本是0.7.0，但是安装之后提示的还是0.6.0。。。。qmsg酱测试推送的时候直接报错  爆了一个array错误，发送失败：array，这样子的。

**Comment by Rainshaw** [comment]
不要同一段话发好几遍。
如果你发完还想补充，可以重新编辑。
问题定位中。

**Comment by Rainshaw** [comment]
我使用最新版，Qmsg测试是没有问题的，请注意你的插件配置。

**Comment by OuOumm** [comment]
> 我使用最新版，Qmsg测试是没有问题的，请注意你的插件配置。

好的，你的php版本是多少？我的是7.0，你估计是7.4吧，个人感觉是这个问题，我正在装载7.4，请稍后。

**Comment by OuOumm** [comment]
测试完了，并不是php版本问题，依旧发送错误，array
![image](https://user-images.githubusercontent.com/43441064/119291451-0673fd80-bc81-11eb-9dc3-d0ceba3dbddb.png)
![image](https://user-images.githubusercontent.com/43441064/119291485-1986cd80-bc81-11eb-9f52-c1d15ce91123.png)

**Comment by OuOumm** [comment]
目前通过直接调用get方式，可以直接发送。

![image](https://user-images.githubusercontent.com/43441064/119291752-8b5f1700-bc81-11eb-96d3-be2f1c47d5fe.png)

**Comment by OuOumm** [comment]
{"success":false,"reason":"指定的QQ号有1个不在您的QQ号列表中","code":500,"info":{}}
这个是在数据库qq字段中找到的报错，问题是。。我加的qq号没错啊= =

**Comment by OuOumm** [comment]
找到问题了，现在的qmsg酱貌似不需要指定qq号了，所以你的那个才报错了array，具体解决方法


在`Plugin.php`、`TestAction.php`中，注释以下行
```
            $postdata = http_build_query(
                array(
                    'msg' => $msg
                    //'qq' => $this->_pluginOption->QmsgQQ
                )
            );
```
![image](https://user-images.githubusercontent.com/43441064/119293146-6029f700-bc84-11eb-9da0-70febb29825b.png)

**Comment by Rainshaw** [comment]
这边查询到，Qmsg并没有下线这个选项。
你是否没有在 https://qmsg.zendee.cn/me.html#/ 增加你要发送的QQ号码。
我这边测试是完全正常的。
