### ISSUE TITLE
用不了

### ISSUE THREAD

**Issue by ghost** [RainshawGao/Typecho-Plugin-Notice#5]
博客系统更新到1.2 
handsome主题
错误显示Fatal error: Declaration of MDCheckbox::input($name = NULL, ?array $options = NULL) must be compatible with Typecho\Widget\Helper\Form\Element::input(?string $name = NULL, ?array $options = NULL): ?Typecho\Widget\Helper\Layout in /www/wwwroot/www.jacksonxe.cn/usr/plugins/Notice/libs/formelement/MDCheckbox.php on line 78

**Comment by Rainshaw** [comment]
试试 0.8.1
